name: AI Agent Flow

on:
  pull_request:
    branches: [main]

jobs:
  ai-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      # 1) Check out repo
      - uses: actions/checkout@v3

      # 2) Set up Node
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Run AI Flow script
      #
      # Note: We do NOT fail the job if the script returns a non-zero exit code,
      # because we want the script to handle logic, do iterative fixes, etc.
      #
      # Alternatively you can let the script return a code at the very end
      # and let the job fail or succeed. Shown below is "the script decides".
      - name: Run AI Flow
        run: |
          npx tsx scripts/ai-flow.ts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
