name: "AI Agent Flow"

on:
  pull_request:
    branches: [main]

jobs:
  ai-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run AI Flow
        run: npx tsx scripts/github-actions/ai-flow.ts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
