name: "CI - Jest + Playwright"

on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Run Jest
        run: npm run test:unit:ci || true

      - name: Run Playwright
        run: npm run test:e2e:ci || true

      - name: Analyze & Possibly Fix Tests
        # We simply call our TS script
        run: npm run analyze-tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
